### ISSUE TITLE
Error While Running ' Model Evaluation ' Function

### ISSUE THREAD

**Issue by Ajay5641** [malnaanah/coleeg#1]
Error : 
Epoch 1/200
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-aba97b48d198> in <cell line: 35>()
     33 # for selected_subjects in [24]:
     34 #   print(selected_subjects)
---> 35 model, results, time_results, subject_results = evaluate_model(model_list,dataset,Bands, data_x, data_y, data_subject_index,fold_num,Folds,epochs, batch_size=64, verbose=verbose, show_summary = show_summary, batch_norm=batch_norm, apply_spectral=apply_spectral,dropout_rate=dropout_rate, align_to_subject=align_to_subject, selected_subjects=selected_subjects, selected_classes=selected_classes, shuffle=shuffle, play_audio=play_audio)

2 frames
/gdrive/MyDrive/Coleeg4/code/coleeg.py in evaluate_model(model_list, dataset, Bands, data_x, data_y, data_subject_index, fold_num, Folds, epochs, batch_size, verbose, show_summary, batch_norm, apply_spectral, dropout_rate, align_to_subject, selected_subjects, selected_classes, shuffle, play_audio, Max_norm)
   1501       # Building and validating  model
   1502       model = build_model(train_x, train_yc, model_type=model_type,show_summary=show_summary, batch_norm=batch_norm ,apply_spectral=apply_spectral,dropout_rate=dropout_rate)
-> 1503       model.fit(train_x, train_yc, epochs=epochs, batch_size=batch_size, verbose=verbose,  validation_data=(test_x, test_yc))
   1504 
   1505       # fixing memory leak

/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py in error_handler(*args, **kwargs)
    120             # To get the full stack trace, call:
    121             # `keras.config.disable_traceback_filtering()`
--> 122             raise e.with_traceback(filtered_tb) from None
    123         finally:
    124             del filtered_tb

/usr/local/lib/python3.10/dist-packages/keras/src/backend/tensorflow/numpy.py in clip(x, x_min, x_max)
    856     if dtype == "bool":
    857         x = tf.cast(x, "int32")
--> 858     return tf.clip_by_value(x, x_min, x_max)
    859 
    860 

ValueError: Tried to convert 'y' to a tensor and failed. Error: None values not supported.

**Comment by Ajay5641** [comment]
Solved

**Comment by malnaanah** [comment]
Would you tell us how it was solved ?

**Comment by Ajay5641** [comment]
I currently don't remember, but it was something related to an environmental issue. Thank you.

**Comment by malnaanah** [comment]
I am facing the same problem now.

If you modified the code or the Colab file, can you provide us with the modified code.

**Comment by Ajay5641** [comment]
https://github.com/user-attachments/assets/fb7c1e1a-d906-4d1a-83fd-326ba666ba8f

Download TensorFlow version 2.15.0 correctly.
